version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todos
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      - PGUSER=admin
      - PGHOST=postgres
      - PGDATABASE=todos
      - PGPASSWORD=password
      - PGPORT=5432
    ports:
      - 3000:3000

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/todos
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=password
      - KC_HOSTNAME=localhost
    ports:
      - 8443:8443
    depends_on:
      - postgres

volumes:
  postgres-data:
