version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todos
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      - PGUSER=admin
      - PGHOST=postgres
      - PGDATABASE=todos
      - PGPASSWORD=password
      - PGPORT=5432
    ports:
      - 3000:3000
volumes:
  postgres-data:
