apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: PGDATABASE
              value: todos
            - name: PGHOST
              value: postgres
            - name: PGPASSWORD
              value: password
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: admin
            - name: PUBLIC_KEY
              value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAroWRdJswnAEZHNxFTXQV2Px+639zbg7ZzitN3zTr2oQahaYdectA1Ep7qNkeXD4rC72Pp6WbxT9yLHTBOvJxWTWYaoCkj/dYd63QF1/ee3INvpqag6e5F2bk2s7gWmJILHt6tB9T/qgU2cHF413FK+vENNMTKquj/RkviL9YBF1iCnRF92ACfoQu82lfQHT3rMWhdG3gwzGGfMskuqvBlwSgn+Kg8zgzn9WonCmClwbdxklUSPxUrBgTdDwS2jMOgXfPDGIXKl1FmE8j4IapWBiSQg2H23ushO2hoDIIPYC3gVn391jJWkN1GhpQPQNWQTZvwl3nAI9mcIQlw8sVWwIDAQAB
          image: mkarnicki1/projekt-chmurowe:backend
          name: backend
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
